/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jikexueyuan_cpplog_LogMsg */

#ifndef _Included_com_jikexueyuan_cpplog_LogMsg
#define _Included_com_jikexueyuan_cpplog_LogMsg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jikexueyuan_cpplog_LogMsg
 * Method:    logMsg
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jikexueyuan_cpplog_LogMsg_logMsg
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
